language: php

php:
  - 7.1
  - 7.2
  - hhvm # on Trusty only
  - nightly

before_script:
  - wget -O vendor/bin/phpunit-5.7 https://phar.phpunit.de/phpunit-5.7.phar

install: travis_retry composer install

notifications:
  email: falsec